## MDS18. ДЗ 02 (лекция "Линейная алгебра. Матрицы").

### 1) Создайте случайную матрицу А1 размерностью 5 на 5

In [1]:
import numpy as np

In [2]:
A1 = np.random.random((5,5))
A1

array([[0.99506968, 0.58430022, 0.8174697 , 0.95716934, 0.03392958],
       [0.87546676, 0.58066123, 0.0623455 , 0.2510612 , 0.94759618],
       [0.24809336, 0.81689179, 0.02251387, 0.16996045, 0.20861915],
       [0.00376958, 0.09292004, 0.67521193, 0.84845778, 0.03982372],
       [0.80984635, 0.57151063, 0.86751103, 0.27901382, 0.20976656]])

### 2) Транспонируйте матрицу A1

In [3]:
np.transpose(A1)

array([[0.99506968, 0.87546676, 0.24809336, 0.00376958, 0.80984635],
       [0.58430022, 0.58066123, 0.81689179, 0.09292004, 0.57151063],
       [0.8174697 , 0.0623455 , 0.02251387, 0.67521193, 0.86751103],
       [0.95716934, 0.2510612 , 0.16996045, 0.84845778, 0.27901382],
       [0.03392958, 0.94759618, 0.20861915, 0.03982372, 0.20976656]])

### 3) Найдите обратную матрицу для А1

In [4]:
np.linalg.inv(A1)

array([[ 1.15426049,  0.20427392, -0.71244096, -1.16048726, -0.18062467],
       [-0.21604652, -0.36653456,  1.49924377, -0.01472038,  0.20247451],
       [-0.93346551, -0.27008601, -0.28406211,  0.68913823,  1.52274652],
       [ 0.81245454,  0.20466622,  0.07734409,  0.59574334, -1.24599143],
       [-1.08785294,  1.05472384, -0.26228732,  0.87799307,  0.27273802]])

### 4) Создайте диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4

In [5]:
A2 = np.random.random((4,4))
A2

array([[0.26691446, 0.10588687, 0.93544006, 0.82845225],
       [0.73849409, 0.11972549, 0.90726435, 0.03481261],
       [0.50161758, 0.80313809, 0.61350933, 0.57941034],
       [0.46209203, 0.5904769 , 0.37989135, 0.83935975]])

In [6]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
A3 = I*A2
A3

array([[0.26691446, 0.        , 0.        , 0.        ],
       [0.        , 0.11972549, 0.        , 0.        ],
       [0.        , 0.        , 0.61350933, 0.        ],
       [0.        , 0.        , 0.        , 0.83935975]])

### 5) Создайте нулевую матрицу размерности 3 на 3

In [8]:
A4 = np.zeros([3,3])
A4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 6) Для всех полученных матриц найдите: определитель, ранг и собственные значения

#### Матрица A1:

In [9]:
np.linalg.det(A1)

0.33961522775182107

In [10]:
np.linalg.matrix_rank(A1)

5

In [11]:
np.linalg.eig(A1)

(array([ 2.39415585+0.j        ,  0.44817847+0.39081204j,
         0.44817847-0.39081204j, -0.31702184+0.54832829j,
        -0.31702184-0.54832829j]),
 array([[ 0.55286304+0.j        , -0.16386718+0.46046167j,
         -0.16386718-0.46046167j, -0.14181627+0.08116339j,
         -0.14181627-0.08116339j],
        [ 0.56321958+0.j        ,  0.37810133-0.10858388j,
          0.37810133+0.10858388j,  0.59198024+0.j        ,
          0.59198024-0.j        ],
        [ 0.30877367+0.j        ,  0.26581053-0.29904183j,
          0.26581053+0.29904183j, -0.13473887-0.55655931j,
         -0.13473887+0.55655931j],
        [ 0.18292774+0.j        , -0.56194235+0.j        ,
         -0.56194235-0.j        , -0.08426263+0.27462501j,
         -0.08426263-0.27462501j],
        [ 0.49831961+0.j        ,  0.27470993-0.2346178j ,
          0.27470993+0.2346178j , -0.39858727+0.23142236j,
         -0.39858727-0.23142236j]]))

In [12]:
np.linalg.eigvals(A1)

array([ 2.39415585+0.j        ,  0.44817847+0.39081204j,
        0.44817847-0.39081204j, -0.31702184+0.54832829j,
       -0.31702184-0.54832829j])

#### Транспонированная матрица A1:

In [13]:
np.linalg.det(np.transpose(A1))

0.33961522775182107

In [14]:
np.linalg.matrix_rank(np.transpose(A1))

5

In [15]:
np.linalg.eig(np.transpose(A1))

(array([ 2.39415585+0.j        ,  0.44817847+0.39081204j,
         0.44817847-0.39081204j, -0.31702184+0.54832829j,
        -0.31702184-0.54832829j]),
 array([[ 0.52517791+0.j        , -0.32881697+0.42424478j,
         -0.32881697-0.42424478j,  0.18178633+0.11079938j,
          0.18178633-0.11079938j],
        [ 0.47170693+0.j        ,  0.02269915-0.11543549j,
          0.02269915+0.11543549j, -0.18671264-0.44209682j,
         -0.18671264+0.44209682j],
        [ 0.43103788+0.j        ,  0.26978026-0.06328867j,
          0.26978026+0.06328867j,  0.6306534 +0.j        ,
          0.6306534 -0.j        ],
        [ 0.49670343+0.j        ,  0.72248108+0.j        ,
          0.72248108-0.j        , -0.056628  -0.1234449j ,
         -0.056628  +0.1234449j ],
        [ 0.26300719+0.j        , -0.09322676-0.3009953j ,
         -0.09322676+0.3009953j , -0.36063815+0.42206286j,
         -0.36063815-0.42206286j]]))

#### Обратная матрица для A1:

In [16]:
np.linalg.det(np.linalg.inv(A1))

2.944508721295514

In [17]:
np.linalg.matrix_rank(np.linalg.inv(A1))

5

In [18]:
np.linalg.eig(np.linalg.inv(A1))

(array([-0.79024952+1.36683381j, -0.79024952-1.36683381j,
         1.26748024+1.10524394j,  1.26748024-1.10524394j,
         0.41768375+0.j        ]),
 array([[ 0.14181627+0.08116339j,  0.14181627-0.08116339j,
          0.16386718+0.46046167j,  0.16386718-0.46046167j,
          0.55286304+0.j        ],
        [-0.59198024+0.j        , -0.59198024-0.j        ,
         -0.37810133-0.10858388j, -0.37810133+0.10858388j,
          0.56321958+0.j        ],
        [ 0.13473887-0.55655931j,  0.13473887+0.55655931j,
         -0.26581053-0.29904183j, -0.26581053+0.29904183j,
          0.30877367+0.j        ],
        [ 0.08426263+0.27462501j,  0.08426263-0.27462501j,
          0.56194235+0.j        ,  0.56194235-0.j        ,
          0.18292774+0.j        ],
        [ 0.39858727+0.23142236j,  0.39858727-0.23142236j,
         -0.27470993-0.2346178j , -0.27470993+0.2346178j ,
          0.49831961+0.j        ]]))

#### Единичная матрица I:

In [19]:
np.linalg.det(I)

1.0

In [20]:
np.linalg.matrix_rank(I)

4

In [21]:
np.linalg.eig(I)

(array([1., 1., 1., 1.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

#### Диагональная матрица А3:

In [22]:
np.linalg.det(A3)

0.016456141935448084

In [23]:
np.linalg.matrix_rank(A3)

4

In [24]:
np.linalg.eig(A3)

(array([0.26691446, 0.11972549, 0.61350933, 0.83935975]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

#### Нулевая матрица А4:

In [25]:
np.linalg.det(A4)

0.0

In [26]:
np.linalg.matrix_rank(A4)

0

In [27]:
np.linalg.eig(A4)

(array([0., 0., 0.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

### 7) Проанализируйте результаты

#### (кое-что, навскидку)))

- определитель транспонированной матрицы совпадает с исходной и не совпадает с обратной
- собственные числа транспонированной матрицы совпадают с исходной, и отличаются от обратной
- собственные вектора исходной, транспонированной и обратной матрицы, как кажется, отличны (хотя из-за того, что там сложный набор чисел, включая комплексные. на глаз это трудно разобрать, а теорию смотреть было лень, извините ...
- определитель единичной матрицы - единица, нулевой - ноль
- похоже, что собственные вектора нулевой, единичной и диагональной матрицы с одинаковым числом столбцов(строк) совпадают