### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N=int(input('Введите целое положительное число: '))

Введите целое положительное число: 10


In [3]:
x=np.flip(np.arange(0, N))
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [ ]:
import numpy as np

In [4]:
N=int(input('Введите целое положительное число: '))

Введите целое положительное число: 7


In [5]:
x=np.flip(np.arange(0, N))
np.diag(x)

array([[6, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [6]:
print("Сумма чисел по диагонали: ", np.trace(np.diag(x)))

Сумма чисел по диагонали:  21


### Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [ ]:
import numpy as np

In [7]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0],[0, 5, 4] ] )

In [8]:
# значения в правой части уравнения

b = np.array( [4, 12, -3] )

In [9]:
from numpy import linalg

In [10]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
#Картинку не нашел, вставил сразу матрицу покупок. Столбец user_id подразумевается.

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [11]:
#В аналогии с векторами мне было проще представить себе алгоритм поиска через минимизацию косинусного расстояния
#И, разумеется, это заготовка функции. Тут, очевидно, должна быть еще проверка соответствия длины вектора матрице.


def similarity (next_user_stats):
    import numpy as np
    import scipy.spatial.distance as ds
    users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
    )
    best={}
    for i in range(len(users_stats)):
        d=users_stats[i]
        best[i] = ds.cosine(users_stats[i],next_user_stats)
    user_id = min(best, key = lambda k: best[k])
    row_closest = users_stats[min(best, key = lambda k: best[k])]
    cosine_similarity = 1-best[min(best, key = lambda k: best[k])]
    
    print("Самый похожий пользователь:", user_id, row_closest, "косинусное сходство:", cosine_similarity)

In [12]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

similarity (next_user_stats)

Самый похожий пользователь: 7 [0 1 1 0 0 0] косинусное сходство: 0.9486832980505138
